config/routes.rb
Rails.application.routes.draw do
  resources :products
  # get 'home/index'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'home/about'
  root "products#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
    has_one_attached :product_picture
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about 
  end 
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:title, :description, :price, :inventory, :product_picture)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Ecom Store", root_path, class:"navbar-brand" %> 
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
          <%= link_to "About", home_about_path, class:"nav-link" %> 
        </li>

        <li class="nav-item">
          <%= link_to "Your Cart", home_about_path, class:"nav-link" %> 
        </li>

        <li class="nav-item">
          <%= link_to "Add Product", new_product_path, class:"nav-link" %> 
        </li>

      </ul>

      <%= form_with url: products_path, method: :get, class:"d-flex" do |form| %>
        <%= form.text_field :query, placeholder: "Search", class:"form-control me-2" %>
        <%= form.submit "Search", class: "btn btn-outline-success" %>
      <% end %>

    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>Who we are ...</h1>

app/views/home/index.html.erb
<h1>Check out our products</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ecom</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'home/header' %> 
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

      <%= yield %>
    </div>


    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.min.js" integrity="sha384-lpyLfhYuitXl2zRZ5Bn2fqnhNAKOAaM/0Kr9laMspuaMiZfGmfwRNFh8HlMy49eQ" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.text_field :title, class:"form-control", placeholder:"Title" %><br>
  </div>

  <div class="field form-group">
    <%= form.text_field :description, class:"form-control", placeholder:"Description" %><br>
  </div>

  <div class="field form-group">
    <%= form.number_field :price, class:"form-control", placeholder:"Price" %><br>
  </div>

 <div class="field form-group">    
    <%= form.number_field :inventory, class:"form-control", placeholder:"Inventory" %><br>
  </div>

 <div class="field form-group">
    <%= form.label "Product Picture" %><br>
    <%= form.file_field :product_picture %><br>
  </div>

  <div class="actions">
  <br>
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Edit your Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<style>
  .col-card {
    padding-bottom: 25px;
  }
</style>


<p id="notice"><%= notice %></p>

<div class="container">
  <div class="row">
    <div class="col">
      <h1>Products</h1><br>
    </div>
    <div class="col-auto">
      <%= link_to 'New Product', new_product_path, class:"btn btn-success" %><br><br>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <% @products.each do |product| %>
      <div class="col col-card">
        <div class="card" style="width: 18rem;">
          <% if product.product_picture.attached? %>
            <img src="<%=(url_for(product.product_picture))%>" class="card-img-top" alt="...">
          <% end %>
          <div class="card-body">
            <h5 class="card-title"><%= product.title %></h5>
            <p class="card-text"><%= product.description %></p>
            <p class="card-text">Price: $<%= product.price %></p>
            <p class="card-text"><%= product.inventory %> Remaining</p>

            <%= link_to 'Show', product, class:"btn btn-primary" %>
            <%= link_to 'Edit', edit_product_path(product), class:"btn btn-warning"  %>
            <%= link_to 'Destroy', product, method: :delete, class:"btn btn-danger", data: { confirm: 'Are you sure?' } %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
 


<br>

app/views/products/new.html.erb
<h1>Add a Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<% if @product.product_picture.attached? %>
  <img src="<%=(url_for(@product.product_picture))%>" class="card-img-top" alt="...">
<% end %>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Inventory:</strong>
  <%= @product.inventory %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>